### ISSUE TITLE
NIRISS SOSS psfs are identical for CLEAR and F277W filters

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#308] opened 2019-06-18 15:17 UTC
Filed by @hover2pi  at https://github.com/mperrin/webbpsf/issues/227:

I noticed that if I generate a NIRISS psf using pupil `GR700XD` and filter `CLEAR` or `F277W`, I get identical psfs returned. They should be different!

Here's the code I used:

```
import webbpsf
ns = webbpsf.NIRISS()
ns.pupil_mask = 'GR700XD'
ns.filter = 'CLEAR'
clear = ns.calc_psf(monochromatic=1E-6, oversample=1)
ns.filter = 'F277W'
f277w = ns.calc_psf(monochromatic=1E-6, oversample=1)
np.all(clear == f277w)
```

Is it the case that only the `CLEAR` filter is supported with `GR700XD` or am I mistaken? And if not, are there plans to add support for the `F277W` filter? Thanks!

**Comment by obi-wan76** [comment] 2019-09-10 20:59
@mperrin a couple of comments regarding this issue:
1. It seems that to enable sos spectroscopy, NIRISS GR700XD grism should only work with the CLEAR filter, by design. Other combinations should be avoided. 
2. It is not clear to me what is the utility of running a monochromatic PSF through a grism. Using a broadband PSF does produce different results. However, as I mentioned, any combination other than GR700XD + CLEAR should be avoided.
3. Finally, looking at the filter files for NIRISS from jdox: https://jwst-docs.stsci.edu/files/73023162/73023163/1/1494860472234/NIRISS_Filters_2017May.tar.gz . There is a big difference between the WebbPSF filter transmission and those from the link (which are supposedly use in the ETC). At least for F277W. Does WebbPSF has the latest filters or should be update the references for Jdox?
![Comp_ETC_WebbPSF](https://user-images.githubusercontent.com/9635910/64650040-31a2b480-d3ec-11e9-8363-cba72db5a3a9.png)

What do you think?

**Comment by hover2pi** [comment] 2019-09-11 15:47
@obi-wan76 GR700XD+F277W is going to be added as an allowed observation mode, mainly so that users can produce a clean first order spectrum without second order contamination since the traces overlap strongly on part of the detector. For simulation and spectral extraction purposes, the GR700XD+F277W psf would be extremely useful.

**Comment by obi-wan76** [comment] 2019-09-11 16:00
@hover2pi thanks for the clarification! I ran a couple of broadband WebbPSF simulations with the CLEAR and F277W filter and found difference in the PSFs. It is true that for monochromatic there is not difference, however, as you can see WebbPSF transmission at 2.77 um is very close to 1, thus, similar to CLEAR. Not sure why is exactly the same PSF, what would be the effect of running a monochromatic PSF through a grating, perhaps, is an expected result? 
As I mentioned, the broadband simulated PSF do show a difference. I am looking into the code to see if there is an enforce condition in the pupil/filter combination when selecting monochromatic calculations. 

In a similar discussion, are the filter files provided in Jdox (link above) the latest one? and for that matter, the one that the ETC is using? I am trying to understand the difference between those files and the one in WebbPSF. 
Thanks!

**Comment by mperrin** [comment] 2019-09-11 16:02
Let me point out that for grism & prism modes, WebbPSF does _not_ model the spectral dispersion as a function of wavelength. That needs to be simulated using some other tool such as aXesim or MIRAGE. WebbPSF can be (should be) used to produce the monochromatic PSFs that get spread out across the detector. But broadband PSFs from WebbPSF for grism modes aren't going to be what you want.

**Comment by mperrin** [comment] 2019-09-11 16:11
@obi-wan76: 
> Finally, looking at the filter files for NIRISS from jdox: https://jwst-docs.stsci.edu/files/73023162/73023163/1/1494860472234/NIRISS_Filters_2017May.tar.gz . There is a big difference between the WebbPSF filter transmission and those from the link (which are supposedly use in the ETC). At least for F277W. Does WebbPSF has the latest filters or should be update the references for Jdox?

Let's recall we need to distinguish between filter transmissions (throughput of the filter alone) and the overall system transmission (a.k.a. relative spectral response or photon conversion efficiency; this includes the filter transmission plus all the other optical surfaces and the detector QE. )

WebbPSF includes the overall transmission, not the individual filters. That's obtained from Pandeia, which is considered the authoritative source of all this via CRDS, ReDCaT, etc. The F277W file in WebbPSF 0.8 is from Pandeia 1.2.2, the one we're about to release in WebbPSF 0.9 is from Pandeia 1.4.

**Comment by obi-wan76** [comment] 2019-09-16 20:08
@hover2pi For monochromatic PSFs the total intensity output is normalized to 1 at the entrance pupil, propagates it through the system and ignoring the transmitted loses from the filters but including the diffraction loses from slits/stops. It is the ETC job to add these missing losses and various other effects. Therefore, going back to the original post, when changing the filters it is expected that the monochromatic PSFs will be the same. You can read more on WebbPSF normalization:
https://webbpsf.readthedocs.io/en/stable/webbpsf.html#psf-normalization

**Comment by hover2pi** [comment] 2019-09-18 15:06
@obi-wan76 @mperrin Ok, so webbpsf works as expected and GR700XD+CLEAR and GR700XD+F277W should look identical since the filter throughputs are not applied. I'll check pandeia. Thanks! Feel free to close this ticket.

**Closed** 2019-09-18 16:19 UTC
