### ISSUE TITLE
seg fault in call to calc_psf

### ISSUE THREAD

**Issue by joel-roediger** [spacetelescope/webbpsf#388] opened 2020-10-21 17:19 UTC
Hello,

Last week I was able to generate a NIRCam PSF image with webbpsf in a jupyter notebook.  When I returned to that notebook today, I find that the notebook kernel dies during the call to calc_psf.  Running the same set of commands within a python session, I get a segmentation fault during the call to calc_psf.  Here is a copy of the terminal output from the python session:

(astro) bash-3.2$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbpsf
>>> nspec = webbpsf.NIRSpec()
>>> nspec.image_mask = 'S200A1'
>>> psfs = {}
>>> for wave in [0.6e-6, 1e-6, 2e-6, 3e-6]:
...     psfs[wave] = nspec.calc_psf(monochromatic=wave, oversample=4)
... 
Segmentation fault: 11

As far as I am aware, nothing has changed with my environment since my previous (successful) use of webbpsf and calc_psf.  Reinstalling webbpsf did not fix the issue.  Any ideas?

Regards,
Joel Roediger

**Comment by mperrin** [comment] 2020-10-21 17:55
Hi @shanosborne, can you please lend a hand to @joel-roediger on investigating and debugging this? Thanks much.

**Comment by shanosborne** [comment] 2020-10-21 18:46
Hi @joel-roediger - I tried to run the same commands on my computer (also a Mac, in a new environment to match your python version, both in a python and ipython session) and I don't get a seg fault error. If you want to create an environment yaml file from your current environment and pass that along to me, I can try building an environment from that and see if I can duplicate your results that way. To create an environment file, get into the environment you're interested in and run `conda env export > environment.yml`. (You may have to save the file as a txt or zip it to be able to upload it to github, I can't remember which file types it accepts)

**Comment by joel-roediger** [comment] 2020-10-21 22:47
Thanks @shanosborne.  Please see attached.

[environment.yml.txt](https://github.com/spacetelescope/webbpsf/files/5419027/environment.yml.txt)

**Comment by joel-roediger** [comment] 2020-10-23 13:23
Hi @shanosborne.  Any news?

**Comment by shanosborne** [comment] 2020-10-23 13:30
Hi @joel-roediger - sorry about the delay. I tried running the commands in an environment made with your `environment.yml` file and unfortunately I'm still not able to reproduce your error. I've been trying to think about what else to compare to try and duplicate your results (sadly, segfault errors are not very descriptive). @mperrin - any ideas?

**Comment by mperrin** [comment] 2020-10-23 13:41
Let's see. This does not particularly sound like a webbpsf issue since we can't reproduce it here. In any case webbpsf and poppy are both pure-python code (no embedded C extensions etc) so it's nearly impossible for them to cause a segmentation fault; not unless there's a deeper issue in one of the lower-level libraries being used, or an installation issue in your environment there that we can't replicate . 

Looking at that environment file however I do see that many of the package versions are quite old (numpy 1.12, vs current 1.19, for instance; intel MKL 2017; and so on. Not to mention webbpsf itself is only 0.8; which surprises me since you said you reinstalled it. Is it pinned to that version in your environment, Joel? ). Unless there is a particular reason you need these versions, I would suggest trying to update your conda environment, or create a new environment using more up-to-date packages.  It's possible that whatever bug you're encountering has been fixed in the mean time, or if it's some other subtle environment issue then it will be addressed by reinstalling. 


If for some reason you can't or choose not to do that, the next steps for debugging would be to look at a full stack trace, or any other debug information printed out from the set fault. Hopefully it prints more than just "Segmentation fault: 11"? The other thing you can do is, prior to your calculation, run `webbpsf.setup_logging('debug')`. This will produce much more verbose output from the calculation, which may help pin down where the problem is occurring, and perhaps thus which lower-level library is at fault.

**Comment by mperrin** [comment] 2021-04-02 15:45
Hi @joel-roediger, I wanted to follow up on this open issue from last fall. Were you able to get your calculation running in the end? Please let us know if there's anything more we can help with, or if it's OK for us to close this issue at this point. Thanks.

**Comment by joel-roediger** [comment] 2021-04-03 05:15
Hi Marshall,

I think it would be alright to close it.

Cheers,
Joel

**Closed as completed** 2021-12-07 07:08 UTC
Labels: bug
